name: Any Updates?
  
on:
  workflow_dispatch:
  schedule:
  - cron: '30 14 * * *'

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Any Updates?
        run: |
          gh issue comment 7 --body 'Any Updates? Let's work on MyScratchBlocks!'
